### ISSUE TITLE
[grocery-bee] Add instructions to README for running project

### ISSUE THREAD

**Issue by ardaOnal** [ardaOnal/grocery-bee#34]
README'ye installdan sonra runlamak hakkında step by step guide yazılmalı

- main.py'ı runlamak
- meshcat simulasyonu için localhost'u aç vb.
- belki kodun runlaması ve konsol output hakkında bilgiler

özgür hocayla kodu paylaşmadan önce yapabilirsek güzel olur

**Comment by efebeydogan01** [comment]
readme updated
